name: Build on Pull Request

on:
  pull_request:

  push:
    branches:
      - renovate-*

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        uses: cypress-io/github-action@v4
        with:
          start: yarn preview

      - if: failure()
        name: Upload failure screenshots
        uses: actions/upload-artifact@v3
        with:
          name: Cypress Screenshots
          path: cypress/e2e/__image_snapshots__/*
          retention-days: 7
